version: '2'

volumes:
  db_data:
  db_logs:
  service_raster:
  service_sslconf:
  
services:
  db:
    image: idgis/geopublisher_database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - PG_USER=publisher
      - PG_PASSWORD=${PG_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql
      - db_logs:/var/log/postgresql
      
  db_init:
    build: publisher-database-init
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DBNAME=publisher
      - PG_USER=publisher
      - PG_PASSWORD=${PG_PASSWORD}
      - DOMAIN_PREFIX=${DOMAIN_PREFIX}
      - DOMAIN_SUFFIX=${DOMAIN_SUFFIX}
  
  zookeeper:
    image: jplock/zookeeper
    restart: always
    
  service:
    image: idgis/geopublisher_service
    restart: always
    ports:
      - "4242:4242"
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DBNAME=publisher
      - PG_USER=publisher
      - PG_PASSWORD=${PG_PASSWORD}
      - GEOSERVER_USER=admin
      - GEOSERVER_PASSWORD=${GEOSERVER_PASSWORD}
      - AKKA_HOSTNAME=service
      - AKKA_LOGLEVEL=DEBUG
      - ZOOKEEPER_HOSTS=zookeeper
      - METADATA_URL_PREFIX=http://${DOMAIN_PREFIX}metadata${DOMAIN_SUFFIX}/metadata/dataset/
      - SSL_CONFIG=/etc/geo-publisher/ssl
      - RASTER_DIR=/var/lib/geo-publisher/raster
    volumes:
      - service_raster:/var/lib/geo-publisher/raster
      - service_sslconf:/etc/geo-publisher/ssl
      
  proxy:
    build: publisher-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_PREFIX=${DOMAIN_PREFIX}
      - DOMAIN_SUFFIX=${DOMAIN_SUFFIX}
    
  web:
    image: idgis/geopublisher_web
    restart: always
    environment:
      - AKKA_HOSTNAME=web
      - SERVICE_HOST=service
      - DATASET_METADATA_URL_PREFIX=http://${DOMAIN_PREFIX}metadata${DOMAIN_SUFFIX}/metadata/dataset/
      - SERVICE_METADATA_URL_PREFIX=http://${DOMAIN_PREFIX}metadata${DOMAIN_SUFFIX}/metadata/service/
    
  metadata:
    image: idgis/geopublisher_metadata
    restart: always
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DBNAME=publisher
      - PG_USER=publisher
      - PG_PASSWORD=${PG_PASSWORD}
      - METADATA_HOST=${DOMAIN_PREFIX}metadata${DOMAIN_SUFFIX}
    
  geoserver_staging:
    image: idgis/geopublisher_geoserver
    restart: always
    environment:
      - GEOSERVER_USER=admin
      - GEOSERVER_PASSWORD=${GEOSERVER_PASSWORD}
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DBNAME=publisher
      - PG_USER=publisher
      - PG_PASSWORD=${PG_PASSWORD}
      - ZOOKEEPER_HOSTS=zookeeper
      - SERVICE_IDENTIFICATION=geoserver-staging
      - SERVICE_DOMAIN=${DOMAIN_PREFIX}staging-services${DOMAIN_SUFFIX}
    
  viewer_staging:
    image: idgis/geopublisher_viewer:1.2
    restart: always
    environment:
      - VIEWER_CONTEXT=/viewer
      - VIEWER_ENVIRONMENT_URL=http://${DOMAIN_PREFIX}staging-services${DOMAIN_SUFFIX}/geoserver/
      - VIEWER_USERNAME=admin
      - VIEWER_PASSWORD=geoserver
    links:
      - proxy:${DOMAIN_PREFIX}staging-services${DOMAIN_SUFFIX}

  geoserver_public:
    image: idgis/geopublisher_geoserver
    restart: always
    environment:
      - GEOSERVER_USER=admin
      - GEOSERVER_PASSWORD=${GEOSERVER_PASSWORD}
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DBNAME=publisher
      - PG_USER=publisher
      - PG_PASSWORD=${PG_PASSWORD}
      - ZOOKEEPER_HOSTS=zookeeper
      - SERVICE_IDENTIFICATION=geoserver-public
      - SERVICE_DOMAIN=${DOMAIN_PREFIX}services${DOMAIN_SUFFIX}
    
  viewer_public:
    image: idgis/geopublisher_viewer:1.2
    restart: always
    environment:
      - VIEWER_CONTEXT=/viewer
      - VIEWER_ENVIRONMENT_URL=http://${DOMAIN_PREFIX}services${DOMAIN_SUFFIX}/geoserver/
      - VIEWER_USERNAME=admin
      - VIEWER_PASSWORD=geoserver
    links:
      - proxy:${DOMAIN_PREFIX}services${DOMAIN_SUFFIX}