
-- <PostgreSQL>
create schema if not exists staging_data;

create view staging_data.gt_pk_metadata as
select 
	'staging_data'::text table_schema, 
	table_name, 
	column_name pk_column, 
	0 pk_column_idx,
	'autogenerated'::text pk_policy,
	null::text pk_sequence
from information_schema.columns
where table_schema = 'staging_data' 
and column_name = table_name || '_id';

create schema if not exists data;

create view data.gt_pk_metadata as
select 
	'data'::text table_schema, 
	table_name, 
	column_name pk_column, 
	0 pk_column_idx,
	'autogenerated'::text pk_policy,
	null::text pk_sequence
from information_schema.columns
where table_schema = 'data' 
and column_name = table_name || '_id';
-- </PostgreSQL>

insert into publisher.version(id) values(65);
