version: '2'

services:
  db:
    image: postgis/postgis:9.6-3.0
    ports:
      - "127.0.0.1:49153:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
  
  geoserver:
    build: geoserver
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - PG_HOST=db
