name: Build project

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8
      
      - name: Build
        env:
          GITHUB_USER: "github"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_HOST: "unix:///var/run/docker.sock"
        run: ./gradlew build
      
      - name: Upload test output
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: "**/build/reports/tests/*"