name: Build Gradle project

on:
  push:
    branches: [ master ]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    services:
      postgis-test:
        image: postgis/postgis:9.6-3.0
        ports:
          - "127.0.0.1:49153:5432"
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=test
      geoserver-test:
        image: idgis/geopublisher_service_geoserver_test:latest
        ports:
          - "127.0.0.1:8080:8080"
        environment:
          - PG_HOST=postgis-test
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew clean build
      env:
        GITHUB_USER: "github"
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        DOCKER_HOST: "http://localhost:2375"
        NO_EXECUTE_DOCKER_COMPOSE: "true"
      